### PR TITLE
Add a GA Workflow for Build Documentation

### PR DESCRIPTION
**Pull request by rocco8773**
1. Add GitHub Action to test documentation build

### CODE REVIEW

**Comment by StanczakDominik** [comment]
Need any help with this? :)

**Comment by rocco8773** [comment]
@StanczakDominik Sorry, just saw your comment.  Sure!  I'm not sure why the check is not properly seeing `plasmapy`.  I was thinking of removing the `plasmapy` dependency anyways.  `plasmapy` is dropping Python support on the same schedule as `numpy`, but I think this documentation helper should support Python versions on a longer time frame.

**Comment by StanczakDominik** [comment]
Whoops. 😅

**Comment by StanczakDominik** [comment]
There's a single remaining warning: https://github.com/PlasmaPy/plasmapy_sphinx/runs/7702235370?check_suite_focus=true#step:5:12


apparently it comes from here:
https://github.com/PlasmaPy/plasmapy_sphinx/blob/5c2008870764a998ac3416a312a4cd972e2012c7/docs/api_static/plasmapy_sphinx.rst

And it's complaining about `plasmapy_sphinx.theme`. That one doesn't really fit the rest of the `plasmapy_sphinx` directory:
```bash
🕙[ 06:30:07 ] ❯ ls plasmapy_sphinx/*
plasmapy_sphinx/__init__.py  plasmapy_sphinx/utils.py

plasmapy_sphinx/autodoc:
__init__.py  __pycache__  automodapi.py

plasmapy_sphinx/automodsumm:
__init__.py  __pycache__  core.py  generate.py

plasmapy_sphinx/directives:
__init__.py  __pycache__  confval.py  event.py

plasmapy_sphinx/ext:
__init__.py  __pycache__  autodoc.py  automodsumm.py  css.py  directives.py

plasmapy_sphinx/__pycache__:
__init__.cpython-310.pyc  utils.cpython-310.pyc

plasmapy_sphinx/theme:
__init__.py  __pycache__  breadcrumbs.html  footer.html  layout.html  static  theme.conf
```


Are you sure that's the right place for that?

- [x] revert [6fcabf1](https://github.com/PlasmaPy/plasmapy_sphinx/pull/1/commits/6fcabf18aeaf66b527d39a0368ef2d3f5faf8de2) before merging

**Comment by StanczakDominik** [comment]
@rocco8773 IIRC 98a7 fixed the last issues we had here, so we can probably merge this, right?

**Pull request merged**
